set relativenumber
set number
set nocompatible            
set showmatch               
set nohlsearch
set incsearch
set ignorecase
set smartcase
set tabstop=4               
set softtabstop=4           
set scrolloff=8
set scroll=10
set expandtab               
set shiftwidth=4            
set autoindent
set mouse=a
set ttyfast
set noerrorbells
set visualbell
